name: pixelcycle
author: Brian Slesinsky
description: A simple paint program that creates animated gifs.
homepage: https://github.com/skybrian/pixelcycle/

environment:
  sdk: '>=2.0.0-dev.65.0 <3.0.0'

dependencies:
  fixnum: ">=0.10.8"
  browser: any

dev_dependencies:
  build_runner: ^0.9.2
  build_web_compilers: ^0.4.1
